### ISSUE TITLE
Execute SQL queries individually (suggestion)

### ISSUE THREAD

**Issue by arc87** [dbcodeio/public#140]
Hi, I have a suggestion as an improvement, 

when writing several SQL queries it would be interesting to be able to execute each query individually (execute button above each query), something similar to how it works in notebooks,

![Image](https://github.com/user-attachments/assets/19a667b1-8c7b-450b-9a69-044632a244f2)

currently when you click on the execute button, all of them are executed the sql queries present in the editor, and the result is not completely readable

![Image](https://github.com/user-attachments/assets/7e9f8336-52b1-4de3-a0f3-3f7f3b0c5d57)

**Comment by mikeburgh** [comment]
I am not a big fan of the execute text above individual statements for a couple of reasons: 
- It clutters up the editor
- How do you know where the statement ends.. it's abstract based on parsing.. so you might think it's just one statement, but if the parser decides it's more than that, you could end up executing multiple statements you did not want.

That's why I went with the select/highligh approach, it becomes explicit what you are about to execute since it's what you highlighted.

I just fixed that 2nd results tab issue over the weekend as I noticed it working on another feature.. hoping to push it tomorrow with DB2 support.

**Comment by mikeburgh** [comment]
Okay I just pushed a fix for the second tab issues in version 1.5.2.... and also a new issue to track interest in the additional codelens option https://github.com/dbcodeio/public/issues/143

Will see how that goes, but I will close this now the bug is fixed and the new issue can continue the discussion around additional execute buttons.
