### ISSUE TITLE
mssql connection error

### ISSUE THREAD

**Issue by emirkabas** [dbcodeio/public#141]
Error:
Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.

---
VSCode Version: 1.95.3
Extension Version: 1.5.1
OS: darwin
Arch: arm64

**Comment by gfane1** [comment]
Yup save button just times out for me...and there is no example connection strings which would be AWESOME...so as to test adding to dbcode.connections

    },
    "dbcode.color.applyToActiveTabBorder": false,
    "dbcode.connections": [
        
    ]
}

**Comment by mikeburgh** [comment]
@emirkabas the trusted connection option is not supported by the node js driver that's being used. I am waiting for that to change, but until it does you will need to use the domain to authenticate. (Note the official SQL Server extension gets around it as they use a separate downloaded driver) 


@gfane1 sounds like you might have a different issue...  What happens when you try and refresh/expand the database field on the new connection form (it effectively tests the connection to retrieve a list of databases) ? 

I don't recommend editing the connections by hand, but here is a spec for a mssql connection..  The config is also documented, so you should get autocomplete when editing the settings.json and adding options.


```json
{
	"connectionId": "333dgtreterfferter",
	"host": "sqlserver.us-east-1.rds.amazonaws.com",
	"port": 1433,
	"driver": "mssql",
	"name": "SQL Server",
	"database": "test",
	"username": "",
	"password": "",
	"savePassword": "yes",
	"connectionTimeout": 30,
	"ssl": true,
	"sslTrustCertificate": false,
}
```

**Comment by mikeburgh** [comment]
Closing this, let me know if you are still having issues.
