### ISSUE TITLE
mssql connection error

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#25]
Error:
Failed to connect to LOST\ROOT in 30000ms

---
VSCode Version: 1.93.1
Extension Version: 1.2.12
OS: win32
Arch: x64

**Comment by mikeburgh** [comment]
Can you provide some more information about the connection details you are using ? auth type mainly. 

It Looks like a named instance you are trying to connect to, does the server have the server browser process running and ports accessible (I guess can you connect to it from other clients?)  

Can you connect to the default instance when you don't supply a name ?

**Comment by devpkr1** [comment]
I am using windows authentication,

for detailed information i am attaching the screenshot, please refer to it.
![Screenshot 2024-10-02 233507](https://github.com/user-attachments/assets/b29f3f39-c966-4b07-acf9-3d1508998085)

**Comment by mikeburgh** [comment]
Thanks, remove the instance name from the host, and enter it in the instance name box.. should work then...

See: 

![372981062-b29f3f39-c966-4b07-acf9-3d1508998085](https://github.com/user-attachments/assets/5c81f5a3-78ae-4285-bf0c-f40f0d3228e2)

**Comment by mikeburgh** [comment]
Can you share a screenshot of the config in datagrip ?

**Comment by devpkr1** [comment]
Sure , screenshot of config of datagrip is attached.
![Screenshot 2024-10-03 010617](https://github.com/user-attachments/assets/0799b680-d036-4e74-8fcd-d2ac9c3876e9)

**Comment by mikeburgh** [comment]
thanks: 

So here is what you need to enter in the extesnion: 
Host: localhost
Instance Name: LOST
Database: ROOT 
(or use the refresh icon to load the databases)

**Comment by devpkr1** [comment]
Issue still not resolved 
![Screenshot 2024-10-03 103727](https://github.com/user-attachments/assets/c0760629-abeb-4f51-a07c-d3e7a50b6377)

**Comment by mikeburgh** [comment]
Do you get a new/different error ?

**Comment by devpkr1** [comment]
same issue

**Comment by mikeburgh** [comment]
I saw in that screenshot you shared the connection was still trying localhost\LOST 

Can you remove the instance name altogether and see if it works ?

**Comment by devpkr1** [comment]
I tried this so many times but connection with MS SQL SERVER is not established , i think there is a problem in SQL SERVER driver you are using in your extension.
I tried to connect using SQL SERVER authentication as well as Windows Authentication but neither works for me.

 i have also attached an screenshot for correction.
![Screenshot 2024-10-04 094956](https://github.com/user-attachments/assets/9d89587d-100d-484a-91be-06ffd0255179)


Thanks and Regards,
Pradeep Kumar

**Comment by devpkr1** [comment]
hi mike ,

I have successfully connected with MS SQL SERVER ,  i am going to attach the settings screenshot for your reference.
![Screenshot 2024-10-04 181925](https://github.com/user-attachments/assets/9f913869-7981-46a9-893b-9923902b8c3b)

Best Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Good news on getting connected! 

So lost is the server's address and SQL Server is not running on your computer (localhost) or do you have LOST setup as your computers name ? 

Doesn't look like it had a named instance of root as you are not using that..

As for windows auth.. you will still need to enter your username and password, and are you in a domain or just a workgroup in windows ? if it's a domain, you need to enter that, otherwise leave it blank and the extension will assume a work group. I will setup a test, you might be able to leave the username/password blank if SQL is installed on your computer.. but I will check that with a test.. 

Once we get this figured out I will tidy up the docs for some of this to make it clearer

**Comment by devpkr1** [comment]
Hi mike,

I am answering your questions one by one , for your reference.
1).   LOST is My Computer's Name.
2).   ROOT is the Instance Name but it's an optional , it is automatically
detected by the SQL SERVER driver when we login by using SQL SERVER
Authentication .
3).   For Windows Authentication :- I tried a lot but still did not get
connected through this , SQL SERVER is installed locally on my Laptop ,
there is no domain...
4).  One thing I will mention is that , there is no need for a username
while using Windows authentication because it is automatically detected . I
have used many database clients , one of which is the Navicat Premium ,
Datagrip. In all of them one thing is common while connecting using Windows
authentication is there is no need to enter USERNAME and PASSWORD..

I hope this will help you to resolve the problem,  also in Documentation.


Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
2. Sort of.. If you have multiple instances installed.. you get the default one if you don't specify the instance name.. but if you want the other named instance, then you need to enter it's name.. and the connection uses the SQL browser service on the machine to find that instance and connect.
 
So you can see here on my test machine, I have two instances.. the default is MSSQLServer, the other instance is named SQLEXPRESS so entering the name SQLEXPRESS in the instance name field will connect me to that separate instance.

<img width="465" alt="Screenshot 2024-10-04 at 1 26 28 PM" src="https://github.com/user-attachments/assets/20d40922-1390-4415-8f7a-2dac93f9f43b">

3. Did you try windows auth entering the username and password for your window account ? it should work, that's one of the tests I have for it, both for a local instance, and remote.. 


4. Yes for those clients you might be able to not enter the login details...  the issue is a bit more complex inside vscode.... Basically the only driver that can take advantage of windows auth in the Javascript world (what VSCode is built on) without needing the login to be entered requires specific builds for electron versions, and ODBC setups which makes it complex to deploy..

MS solves this another way... they download a package they have built. If you install the MS SQL Server extension you can see it downloads a binary package after installing: 

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: darwin, arm64 (OSX)

Installing SQL tools service to /Users/mike/.vscode/extensions/ms-mssql.mssql-1.24.0/sqltoolsservice/5.0.20240823.2/OSX.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/5.0.20240823.2/microsoft.sqltools.servicelayer-osx-arm64-net8.0.tar.gz
(77078 KB) .................... Done!
Installing ...
Done! 852 files unpacked.
```

They then proxy all the connections and commands through that, which gets them access to the integrated auth (and some other things).

At this stage, that's a lot of work to pick up, so for now, you will need to enter the username and password for windows auth.. not ideal... but until a better driver comes along, or I get time to figure out how to use their sqltools service (which I think they license for anyone to use) there is not a lot of options.

**Comment by devpkr1** [comment]
Hi Mike,

I appreciate the efforts you are putting on, and I also agree with your
points whatever you said.

Thanks a lot for the support

I have made a list of UI enhancements for DB code extension.
But I will sent you one by one for better understanding and enhancements.


Best regards,

Pradeep Kumar

**Comment by devpkr1** [comment]
Hi Mike,

I appreciate the efforts you are putting on, and I also agree with your
points whatever you said, but i tried many times and **not successfully connected using "Windows Authentication".**

In my case **instance name is ROOT**  as shown in **SQL SERVER Configuration manager**
SQL SERVER hosted locally on my laptop there is no domain.
I am attaching screenshot of connection setting and and error i got for Windows Authentication.

![Screenshot 2024-10-05 114835](https://github.com/user-attachments/assets/097ff835-e175-4529-8fbd-7847ab471adf)
![Screenshot 2024-10-05 114756](https://github.com/user-attachments/assets/145a3d07-b4b5-46a5-997d-386384a565a7)

Thanks a lot for the support

I have made a list of UI enhancements for DB code extension.
But I will sent you one by one for better understanding and enhancements.


Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Hmm, let me try and replicate it.. I cannot get it to throw that error in my tests when using a U/P.. are you sure you computer is not in a domain?

**Comment by devpkr1** [comment]
Hi mike,

Yeah i checked in there is no domain set up is done in my Laptop, one thing i was noted in different database clients that is they are using "Trust server certificate" check box while establishing MSSQL connection .
They don't require any Domain to enter while connection setup.


Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Trust server cert is there, it's in the SSL option if you tick the SSL box.. it's a bit different though.. It's for trusting the potentially self signed cert the server maybe using/presenting.

Trusted connection is about trusting the permissions (user account) the binary is running under (or something to that effect, I have not dug to far into it)

If you check the other vscode extensions for SQL Server support, I don't believe any of them work with the trusted connection option except the MS one that downloads that additional package.. but if you look at the reviews, that package makes it super slow (I believe they are serializing the json back and forth of std input/output which will be slow).

There is a binary package that will support trusted connection but it requires compling for each OS/architect and electron version, which gets to be a big list quick.. (eg here is the SQL lite list https://github.com/dbcodeio/public/tree/main/packages/better-sqlite3) 

I want to get the error you having with the windows auth and u/p based login happening on my end so I can track it down.. then once a few other features are done I will look into compiling that binary for all the various combinations and see if it's stable, but that's probably a long way off.

**Comment by mikeburgh** [comment]
I looked the MS one in more detail, lots of complaints about it being slow.. which is due to it using that external binary and needing to serialize all the data back and forth (I think) so that's not really a viable option. 

So for now there is no solution to using the trusted connection method from Node (VSCode) I am watching to see if they add it to the node driver, and if they do, will pick it up.
