### ISSUE TITLE
Feedback on Pre-Release Update: MySQL/MariaDB Create/Edit Table Feature

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#48]
Hi Mike,

I’ve reviewed the pre-release update for the Create/Edit Table feature for MySQL/MariaDB, and I’ve noticed a few issues:

The Save button is not functioning as expected.
The Table Name field is missing. When creating a table, there should be an option to assign a name, and when editing, the table name should be available for renaming.
I understand that you’ve already mentioned that the Primary Key and Indexes tabs are coming soon. I would also suggest adding a Triggers tab, allowing users to create/edit triggers directly from there.

For your reference, I’m attaching a screenshot.
![Screenshot 2024-10-10 103526](https://github.com/user-attachments/assets/2a0fbc87-7d22-45b1-aa7e-732d07af7c01)

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Thanks, yes it's not functional yet in terms of saving.. needs to get a lot of tests written for all the various combos of changes that are possible.

I was going to prompt for the name when saving if it's a new table, and otherwise just display it when editing.. I don't think any SQL servers let you change the name along with altering columns.. so I was going to keep rename as it's own action (it's there now by right clicking on a table).

Triggers is a good idea, but I think I will keep them like store procs, and open them in their own tab.. that way you get the full editor.. anything in these "windows" where you have custom UI, you cannot also get the full editor and hence you loose all the other benifits.. I could show the triggers maybe and clicking on them just opens a new tab.

**Comment by mikeburgh** [comment]
I just pushed an updated pre release, table editing and creation is there and working.

I still need to work on the UX and getting a preview of the SQL you are creating while you change things somwhere on the page.. but otherwise it's getting a lot closer.

**Comment by devpkr1** [comment]
Hi Mike,

Changes in " Nullable " column is not saving , otherwise it is working fine. And if possible please add " Indexes " Tab also.

![Image](https://github.com/user-attachments/assets/6f5bfabb-36d0-4ae6-b273-67dd588ba720)

Thanks and Regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Thanks, found a few other issues I cleaned up, and got the SQL preview appearing.. Need to do some polish on the overall layout, but releasing a new regular version so people can start trying it out. 

The SQL preview is only working in light or dark theme at the moment.. need to figure out how to get the real vscode theme and use that.

Will close this and let new tickets track specific issues that come up
