### ISSUE TITLE
Issue with Editing Cell Values

### ISSUE THREAD

**Issue by devpkr1** [dbcodeio/public#65]
Hi Mike,

I hope this message finds you well.

I wanted to commend you on successfully implementing the feature that allows setting a null value for any cell that accepts it—it's working perfectly!

However, I'm encountering an issue when editing cell values by double-clicking. After making changes, the save button in the header does not become active, and "Apply changes" button is also not appearing at the bottom .

I've attached a screenshot for your reference. Could you please look into this issue?
![Image](https://github.com/user-attachments/assets/d1974d53-5f53-4e04-b724-ba1f33ff0257)

Thank you for your assistance!

Best regards,
Pradeep Kumar

**Comment by mikeburgh** [comment]
Thanks!

The issue is the cell you are in and editing still has focus.. you can see that border around it... 

The change wont be detected until it looses focus. Tab, enter, or clicking somewhere else in the area will cause that to happen.

It's done this way so you can press esc to cancel out of the edit and not trigger the change detection.. 

Re open this if it's working differently for you.
