### ISSUE TITLE
mariadb introspection error

### ISSUE THREAD

**Issue by pmsorensen** [dbcodeio/public#71]
Error:
FUNCTION ****.JSON_ARRAYAGG does not exist

---
VSCode Version: 1.94.2
Extension Version: 1.3.7
OS: linux
Arch: x64
Database Version: Debian 10 - 10.3.18-MariaDB-0 deb10u1-log

**Comment by mikeburgh** [comment]
Thanks, it appears that version 10.5 contains the JSON_ARRAYAGG and JSON_OBJECTAGG functions that I use in introspection.

I will look at making a version without those, but it will involve some re working to get it to support it, so not going to be a quick enhancement

For now I have added a check on the version if it's less than 10.5

**Comment by mikeburgh** [comment]
Fixed in 1.3.11, give it a try and let me know if you have any issues.

**Comment by pmsorensen** [comment]
Hi,
I now get this error:




Error:
Invalid use of group function

---
VSCode Version: 1.94.2
Extension Version: 1.3.12
OS: linux
Arch: x64
Database Version: Debian 10 - 10.3.18-MariaDB-0 deb10u1-log

Should I raise an issue?

best, Peter

**Comment by mikeburgh** [comment]
I have tracked it down to a bug in the group_concat function. 

It was fixed in either version 10.3.33 or 10.3.34. I suspect it was fixed in .33 as .34 was a release to fix a problem in .33

The introspection runs in version 10.3.34 without issue, but throws this error in 10.3.32 and below (10.3.33 is no longer available due to what I assume was the reason for .34 release).

Nothing is jumping out at me on this list [https://mariadb.com/kb/en/mariadb-10333-changelog/](https://mariadb.com/kb/en/mariadb-10333-changelog/) so not sure how to work around it at this stage.

**Comment by pmsorensen** [comment]
Thanks a lot for looking into this. When we get around to upgrade our
servers I'll surely give it another try and let you know.

Cheers, Peter

**Comment by mikeburgh** [comment]
Ahh, sorry I should have been clearer, was still going to attack it, just didn't have much of an idea what was causing it. I tracked it down to something to do with nested GROUP_CONTACT calls inside CTE's but couldn't seem to work around it so moved some of the logic out of SQL. <br><br>Give it a try now and let me know how it goes, I tested it on a 10.3.10 version without issues.

**Comment by mikeburgh** [comment]
Found a small bug with foreign keys, 1.3.15 fixes it, I will close this, re open it if you are still having issues.
