### ISSUE TITLE
Tunnel configuration 

### ISSUE THREAD

**Issue by syxys1** [dbcodeio/public#8]
Trying to configure a new connexion for MariaDB using an ssh tunnel.  The tunnel configuration do not seem to record (save) the private key file.  I have try the standard key format or the .ppk format.  There is no button to test the tunnel connexion so I just save the configuration.  Whenever I reopen the tunnel configuration there is no key file selected.

When I try the new connection using the tunnel, I get an error (conn:-1, no: 45028, SQLState:HY000).

**Comment by mikeburgh** [comment]
Ahh, indeed.. the fields are not showing the key files when you edit, we will get that fixed and released shortly. You should be able to use the standard key format.

When you use the tunnel, does it show connected in the tree view section when you attempt to open the DB ? See below screen shot, it will get a tick on the icon and an arrow appears to expand it. 

<img width="426" alt="Screenshot 2024-05-14 at 9 09 43 AM" src="https://github.com/dbcodeio/public/assets/1918994/dc3414d3-1092-4e2d-9c8a-5353a0087d9a">

If this happens then the tunnel is connected and something else is wrong.. which I think is what's happening as you would be getting an error about the tunnel not connecting in the format: Error opening tunnel <NAME>: <ERROR> if the problem was the tunnel.

**Comment by mikeburgh** [comment]
We just pushed a new release for our MongoDB functionality. We also added some logging to the output tab around opening connections and tunnels, it should hopefully show if the issue is in the tunnel connection or the DB.

**Comment by mikeburgh** [comment]
We just published an update that fixes editing the tunnel (and connection) configuration to show the files previously selected. If you are still having issues with the tunnel, please reopen this issue and we can investigate further.
